### ISSUE TITLE
No coverage when addon/ember-app and package name don't match

### ISSUE THREAD

**Issue by villander** [ember-cli-code-coverage/ember-cli-code-coverage#340]
I noticed that [this support](https://github.com/kategengler/ember-cli-code-coverage/issues/45) is not working on beta versions of this addon. If I have ember apps, add-ons, and engines using scoped package names like `@foo/customers` the coverage stop working. I'm sure that it's a regression issue on **2.0.0-beta.2** since it's working on **1.0.3** version.

**Minimal reproduction** - https://github.com/villander/worspace-example

cc: @kategengler @rwjblue

**Comment by robinborst95** [comment]
@villander @rwjblue in our app we also run into this issue, and I've found that it's because of the way `namespace` is [defined](https://github.com/kategengler/ember-cli-code-coverage/blob/master/packages/ember-cli-code-coverage/lib/attach-middleware.js#L79):
```js
let namespace = relativePath.split(path.sep)[0];
```

When the package name includes a `/`, the found namespace would be `@foo` in this case. The `namespaceMappings` would have a mapping from `@foo/customers` to the `addon` directory, but it's never tried to be retrieved with a namespace `@foo/customers`. I don't know if this is something that is easy to resolve, but namespaced package names are not uncommon I believe, so it might to good to give it a thought.

There is a solution for this though that worked for us, which is using the `modifyAssetLocation` function that has been added in the beta.4 version and can be used like so:
```js
modifyAssetLocation(root, relativePath) {
  if (relativePath.startsWith(name)) {
    return relativePath.replace(name, 'addon');
  }

  return false;
}
```
with `name` being the addon name retrieved from the `package.json` (to prevent hardcoding it).

If no easy solution without such customization is possible, then I guess it is an idea to add something like above to the Readme. What do you think?

**Comment by RobbieTheWagner** [comment]
@robinborst95 I tried your suggestion:

```js
modifyAssetLocation(root, relativePath) {
  if (relativePath.startsWith(name)) {
    return relativePath.replace(name, 'addon');
  }

  return false;
}
```

But it does not seem to work for me. Can you elaborate on how exactly you have things setup?

**Comment by robinborst95** [comment]
@RobbieTheWagner I'll see if I can add a test case here to illustrate it, but in our (v1) addons we literally have this as `tests/dummy/config/coverage.js`:

```js
const { name } = require('../../../package');

module.exports = {
  modifyAssetLocation(root, relativePath) {
    if (relativePath.startsWith(name)) {
      return relativePath.replace(name, 'addon');
    }

    return false;
  }
};
```

**Comment by RobbieTheWagner** [comment]
@robinborst95 I think I have a fix, just opened a PR

**Comment by RobbieTheWagner** [comment]
@robinborst95 @villander this should be fixed in 3.0.0

**Comment by villander** [comment]
Thank you so much @RobbieTheWagner

**Comment by RobbieTheWagner** [comment]
> Thank you so much @RobbieTheWagner

You're welcome! Sorry it took so long.
